### ISSUE TITLE
V1.0.0 Roadmap

### ISSUE THREAD

**Issue by shadowgate15** [breejs/bree-desktop#1]
- [x] connections management
  - [x] add connections
  - [x] remove connections
- [x] edit file button for `localhost` connections
- [x] view configs
- [x] stats for dashboard view
- [x] log output - just send over sse

### Optional
- [ ] [ssh tunnel](https://github.com/luin/medis/blob/d7b798ab751fc26eeea5aa4c874cdc257d58e789/src/renderer/redux/actions/connection.js#L28-L40) for secure connection to server

**Comment by titanism** [comment]
- [ ] Change package name https://github.com/breejs/bree-desktop to https://github.com/breejs/desktop (also make sure to update `.git/config` and `package.json` references
- [ ] Update references, e.g. https://github.com/breejs/bree-desktop/blob/main/package.json#L2 would be `@breejs/desktop` (make sure all references `bree-desktop` get renamed to `desktop`, use `rg` if necessary)
- [ ] Add `private: true` in the package.json
- [ ] Not critical but being able to CMD+F or CTRL+F aka search inside Bree desktop (what do other projects do on Tauri?) -- this would be useful for searching through log output and across Bree desktop in general (maybe a modal with results? not sure, using the native search functionality would be nice)
- [ ] Maybe make the actual output (not the "worker message" or "worker deleted" events, but the actual message received be wrapped inside a `bg-dark` container for `<pre><code>` or something like GitHub Actions Workflow terminal-looking output (what does Bootstrap provide for this?)
- [ ] `= message` .. that would get changed to something like `pre: code!= splitLines(message).join('<br />')` ... where `const splitLines = require('split-lines');` + you'd also need to escape HTML on `message` so it doesn't get rendered, instead `>` would become `&gt;`
- [ ] "Last Run: Never" state gets reset when you reconnect (maybe make it say "Actively running..." and change text when the color changes too)
- [ ] Add "Next run: ..." next to the job name (e.g. a job that starts on a Date, or has an interval or a schedule)
- [ ] Total Waiting color (orange) doesn't correlate
- [ ] @breejs/api needs to have `Bree.extend(plugin, { jwt: false });` example in README
- [ ] @breejs/api probably should have `jwt: false` as a default (?)
- [ ] Pause/stop/start doesn't seem to work on connection state button/status
- [ ] Peer dependency in `package.json` needs be `>= 9` instead of `~9.0`
- [ ] In the Config modal, make the values be wrapped with `<code>` when rendered
- [ ] Filtering doesn't work on the Dashboard

**Comment by titanism** [comment]
- [ ] Multiple connections of the same host/port can be made (this shouldn't be allowed - also the toggle buttons for stop/start didn't seem to affect anything when this occurs - should investigate API side on that)

<img width="1553" alt="Screen Shot 2022-08-15 at 4 54 15 PM" src="https://user-images.githubusercontent.com/101466223/184725024-1a429e41-12e7-429e-9db3-778d4945b4eb.png">

**Comment by titanism** [comment]
- [ ] Use "Tabs" concept vs. Sidebar?
- [ ] Full-screen mode has issues redrawing sidebar (ignore if switching to "Tabs" concept)

<img width="2560" alt="Screen Shot 2022-08-15 at 4 57 10 PM" src="https://user-images.githubusercontent.com/101466223/184725499-de7d215e-b456-437c-b903-df0edc7264f9.png">
